layoutparser 0.3.4
AnacondaRecipes/layoutparser-feedstock pull request #1
Opened 2024-12-31 12:54 UTC by boldorider4

layoutparser 0.3.4 

**Destination channel:** Defaults

### Links

- [PKG-6342]
- dev_url:        No/tree/
- conda_forge:    none
- pypi:           https://pypi.org/project/layoutparser/0.3.4
- pypi inspector: https://inspector.pypi.io/project/layoutparser/0.3.4

### Explanation of changes:

- new version number

2024-12-31 12:55 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_95_q1fyktq/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:44: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:44: missing_documentation: The recipe is missing a doc_url or doc_source_url
- clone/recipe/meta.yaml:19: missing_wheel: For pypi packages, wheel should be present in the host section
- clone/recipe/meta.yaml:44: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:44: missing_dev_url: The recipe is missing a dev_url
===== Final Report: =====
4 Errors and 1 Warning were found

</details>

2024-12-31 13:24 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_97pu5qfwgu/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:44: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:19: missing_wheel: For pypi packages, wheel should be present in the host section
- clone/recipe/meta.yaml:44: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:44: missing_dev_url: The recipe is missing a dev_url
- clone/recipe/meta.yaml:44: missing_documentation: The recipe is missing a doc_url or doc_source_url
===== Final Report: =====
4 Errors and 1 Warning were found

</details>

2024-12-31 13:35 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_f2dd59qxqv/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:46: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:40: missing_pip_check: For pypi packages, pip check should be present in the test commands
- clone/recipe/meta.yaml:46: missing_dev_url: The recipe is missing a dev_url
- clone/recipe/meta.yaml:46: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:19: missing_wheel: For pypi packages, wheel should be present in the host section
- clone/recipe/meta.yaml:46: missing_documentation: The recipe is missing a doc_url or doc_source_url
===== Final Report: =====
5 Errors and 1 Warning were found

</details>

2024-12-31 13:49 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_12c_zxf6wp/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:46: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:46: missing_documentation: The recipe is missing a doc_url or doc_source_url
- clone/recipe/meta.yaml:46: missing_dev_url: The recipe is missing a dev_url
- clone/recipe/meta.yaml:46: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:40: missing_pip_check: For pypi packages, pip check should be present in the test commands
- clone/recipe/meta.yaml:19: missing_wheel: For pypi packages, wheel should be present in the host section
===== Final Report: =====
5 Errors and 1 Warning were found

</details>

2024-12-31 13:55 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_45zehff5zs/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:48: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:21: missing_wheel: For pypi packages, wheel should be present in the host section
- clone/recipe/meta.yaml:48: missing_dev_url: The recipe is missing a dev_url
- clone/recipe/meta.yaml:48: missing_license_family: The recipe is missing the `about/license_family` key.
- clone/recipe/meta.yaml:48: missing_documentation: The recipe is missing a doc_url or doc_source_url
- clone/recipe/meta.yaml:42: missing_pip_check: For pypi packages, pip check should be present in the test commands
===== Final Report: =====
5 Errors and 1 Warning were found

</details>

2024-12-31 14:02 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_ec_9lakxxy/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:54: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-12-31 14:05 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_950m3rjr39/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:56: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-02 18:01 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_83s5ylkiz8/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:73: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-03 11:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_91_sc0j35j/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:77: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-03 12:01 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_66tf1d4x_m/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:77: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-03 12:22 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_1fwsncs04s/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:85: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-06 13:23 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_020bl3u13s/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:85: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-06 14:55 UTC, ifitchet commented
`feedstock-tool` is saying no `README` file?

2025-01-06 15:48 UTC, boldorider4 commented
> `feedstock-tool` is saying no `README` file?

That's right! I forgot to add it! Thank you.

2025-01-06 15:55 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_2agy1fng0w/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:85: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-06 19:49 UTC, ViridianMelody commented on recipe/meta.yaml
> +{% set tests_to_ignore = tests_to_ignore + "--ignore=tests/test_ocr.py" %}
```suggestion
# skip tesseract test on win
{% set tests_to_ignore = "" %}
{% set tests_to_ignore = tests_to_ignore + "--ignore=tests/test_ocr.py" %}  # [win]
```

Assuming you only intended to skip this test on Windows.

2025-01-06 19:49 UTC, ViridianMelody commented on recipe/meta.yaml
> +    folder: github
Is there a reason to use both sources here? I see that the Pypi source is missing the test suite, but I'd think we could just use the Github source.

2025-01-07 09:36 UTC, ifitchet commented on recipe/meta.yaml
> +    - docutils ==0.16
We're building `google-cloud-vision` 3.8.1 so this constraint prevent us installing it.

We don't have `sphinx` 3.0.0 so this constraint prevents us installing it.

We don't have `docutils` 0.16 for `linux-aarch64` or `osx-arm64` (as an observation).

2025-01-09 15:09 UTC, boldorider4 commented on recipe/meta.yaml
> +    folder: github
It's a think I got accustomed to doing, others may find it odd, but I always like the idea that the build itself comes from a PyPi tarball which may slightly differ from the GH tarball. Usually, it's not, but it's just a dogmatic thing I think makes sense.

2025-01-09 15:10 UTC, boldorider4 commented on recipe/meta.yaml
> +    - docutils ==0.16
I see your points! Let me relax these a bit.

2025-01-09 15:13 UTC, boldorider4 commented on recipe/meta.yaml
> +{% set tests_to_ignore = tests_to_ignore + "--ignore=tests/test_ocr.py" %}
Done!

2025-01-09 15:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_b032h92dh6/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:86: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-09 17:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_683y0_xhit/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:86: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-09 17:12 UTC, boldorider4 commented on recipe/meta.yaml
> +{% set tests_to_ignore = tests_to_ignore + "--ignore=tests/test_ocr.py" %}
Oh, actually I did skip this module altogether because of failures on `osx-*`

2025-01-09 17:53 UTC, ifitchet commented on abs.yaml
> +  - https://staging.continuum.io/prefect/fs/pdfplumber-feedstock/pr2/d3d3aaf
Can we build for 3.13 as well?

2025-01-09 17:55 UTC, ifitchet commented on recipe/meta.yaml
> +    # pdfplumber X.X.X has requirement pdfminer.six==YYYYMMDD, but you have pdfminer-six 0.0.1.
The `pdfminer-six` thing should have been fixed now.

2025-01-09 19:22 UTC, ViridianMelody approved these changes

2025-01-09 20:54 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_91bvq3w7uz/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:84: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-10 09:40 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - google-cloud-vision >1.0.0,<2
```suggestion
    - google-cloud-vision >=1.0.0,<2
```

2025-01-10 09:40 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - recommonmark >=0.6.0
I don't see these packages in setup.py https://github.com/Layout-Parser/layout-parser/blob/v0.3.4/setup.py#L48-L72. Where did they come from? 
And missing paddlepaddle==2.1.0 (paddlepaddle >=2.1.0,<3.0.0)?

2025-01-10 09:41 UTC, skupr-anaconda requested changes, later dismissed

2025-01-10 09:41 UTC, skupr-anaconda commented on abs.yaml
> +ANACONDA_ROCKET_ENABLE_PY313 : yes
```suggestion
build_env_vars:
  ANACONDA_ROCKET_ENABLE_PY313 : yes
```
indentation!

2025-01-10 11:30 UTC, boldorider4 commented on recipe/meta.yaml
> +    - recommonmark >=0.6.0
They are the dev-requirements. Admittedly, these may be the requirements for the CI, the docs or maybe some of the tests. I will remove them or move them to the test section if necessary!

2025-01-10 11:32 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_c66_6jbpxw/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:84: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-10 11:36 UTC, skupr-anaconda commented
`- nothing provides requested pdfplumber`

2025-01-10 11:44 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_a8g9rfb5lp/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:81: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-10 14:06 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_2fvm7f36d9/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:81: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-10 14:16 UTC, skupr-anaconda commented
Hmm... 
`CondaHTTPError: HTTP 502 BAD GATEWAY for url <https://conda.anaconda.org/sfe1ed40/linux-64/pypdfium2-4.19.0-py39h06a4308_1.conda>`
Should we reopen the PR?

2025-01-10 14:19 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - opencv
`opencv` isn't available for **py313**:
```
opencv                         4.6.0 py310h46d7db6_3  repo/main
opencv                         4.6.0 py310hc90a7da_5  repo/main
opencv                         4.6.0 py310he2359d5_0  repo/main
opencv                         4.6.0 py310he2359d5_1  repo/main
opencv                         4.6.0 py310he2359d5_2  repo/main
opencv                         4.6.0 py311h6956b77_3  repo/main
opencv                         4.6.0 py311hbae66a1_5  repo/main
opencv                         4.6.0 py312h2e348d3_5  repo/main
opencv                         4.6.0  py38h78102c4_3  repo/main
opencv                         4.6.0  py38h8794c10_0  repo/main
opencv                         4.6.0  py38h8794c10_1  repo/main
opencv                         4.6.0  py38h8794c10_2  repo/main
opencv                         4.6.0  py38hc90a7da_5  repo/main
opencv                         4.6.0  py39h78102c4_3  repo/main
opencv                         4.6.0  py39h8794c10_0  repo/main
opencv                         4.6.0  py39h8794c10_1  repo/main
opencv                         4.6.0  py39h8794c10_2  repo/main
opencv                         4.6.0  py39hc90a7da_5  repo/main
opencv                        4.10.0 py310h69cb8f9_0  repo/main
opencv                        4.10.0 py311h92f7fcd_0  repo/main
opencv                        4.10.0 py312h266819b_0  repo/main
opencv                        4.10.0  py38h69cb8f9_0  repo/main
opencv                        4.10.0  py39h69cb8f9_0  repo/main
```

2025-01-10 14:24 UTC, boldorider4 commented on recipe/meta.yaml
> +    - opencv
skipped `py313`.

2025-01-10 14:24 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_6fqc738f4f/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:83: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-10 14:28 UTC, skupr-anaconda commented
```
conda search pytesseract --subdir=osx-arm64
Loading channels: done
# Name                       Version           Build  Channel
pytesseract                   0.3.10 py310hca03da5_0  repo/main
pytesseract                   0.3.10 py311hca03da5_0  repo/main
pytesseract                   0.3.10 py312hca03da5_0  repo/main
pytesseract                   0.3.10 py313hca03da5_0  repo/main
pytesseract                   0.3.10  py38hca03da5_0  repo/main
pytesseract                   0.3.10  py39hca03da5_0  repo/main
```
and
```
conda search pytesseract --subdir=linux-64
Loading channels: done
# Name                       Version           Build  Channel
pytesseract                   0.3.10 py310h06a4308_0  repo/main
pytesseract                   0.3.10 py311h06a4308_0  repo/main
pytesseract                   0.3.10  py37h06a4308_0  repo/main
pytesseract                   0.3.10  py38h06a4308_0  repo/main
pytesseract                   0.3.10  py39h06a4308_0  repo/main
```
`pytesseract 0.3.10` doesn't have **py312+** on `linux-64`. It should be rebuilt, though

2025-01-10 14:54 UTC, ifitchet commented
> `pytesseract 0.3.10` doesn't have **py312+** on `linux-64`.

More intriguingly, it looks like `pytesseract` was only rebuild for `py312`+ on ARM systems (linux and osx).
Also, not available on `win-64`.

2025-01-10 15:27 UTC, ifitchet commented on recipe/meta.yaml
> +    - google-cloud-vision >=1.0.0,<2
This constraint is too tight (unless it's what you want).  We only have `google-cloud-vision` on SF at version 3.8.1

2025-01-13 11:29 UTC, boldorider4 commented on recipe/meta.yaml
> +    - google-cloud-vision >=1.0.0,<2
It is what I want and through upstream tests I learned that is in fact really necessary. I can even go as far as saying that not all `1.*.*` would probably maintain API consistency.
I know it wouldn't be installable with `google-cloud-vision` in that case. But it's a risk I'm willing to take. Worst case scenario we will rebuild `gcs`.

2025-01-13 14:10 UTC, ifitchet commented on recipe/meta.yaml
> +    - google-cloud-vision >=1.0.0,<2
That's good enough for me.

2025-01-14 18:44 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_00yyjjlw34/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:83: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-15 09:55 UTC, ifitchet commented on recipe/meta.yaml
> +    # pdfplumber X.X.X has requirement pdfminer.six==YYYYMMDD, but you have pdfminer-six 0.0.1.
So `pip check` is back on the menu, then?

I just tried it and it was fine.

2025-01-15 09:56 UTC, ifitchet commented on recipe/meta.yaml
> +  #   - pip
In other words, uncomment these.

Lorenzo liked to reorder these sections as [`source_files`], `imports`, `requires`, commands` giving some top-to-bottom readability.

2025-01-15 09:58 UTC, ifitchet commented on recipe/meta.yaml
> +    # pdfplumber X.X.X has requirement pdfminer.six==YYYYMMDD, but you have pdfminer-six 0.0.1.
remove these

2025-01-15 10:01 UTC, ifitchet commented on recipe/meta.yaml
> +    - google-cloud-vision >=1.0.0,<2
Actually, I wonder is a quick comment stating that you've widened the upstream pinning but deliberately not enough for our own `google-cloud-vision`.  Then next time through people are not scratching their heads (as much) as to your intention.

2025-01-15 10:07 UTC, ifitchet commented on recipe/meta.yaml
> +    - paddlepaddle >=2.1.0,<3.0.0
Again, do we want a comment (for future visitors) as to why we widened the constraint?

2025-01-15 10:08 UTC, ifitchet approved these changes
`pip check`, please; add some comments; all good

2025-01-15 10:24 UTC, skupr-anaconda approved these changes

2025-01-15 13:46 UTC, merged

2025-01-15 13:47 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_84bk2tvnht/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:83: invalid_url: https://layout-parser.readthedocs.io : Not reachable: 403
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2025-01-24 09:58 UTC, lorepirri commented on recipe/meta.yaml
> +    # pdfplumber X.X.X has requirement pdfminer.six==YYYYMMDD, but you have pdfminer-six 0.0.1.
we missed this apparently

2025-01-24 10:04 UTC, Andrii-Osipov commented on recipe/meta.yaml
> +    # pdfplumber X.X.X has requirement pdfminer.six==YYYYMMDD, but you have pdfminer-six 0.0.1.
@lorepirri 
fix:
https://github.com/AnacondaRecipes/pdfminer.six-feedstock/commit/f01b6832bde8900fd6edaf4a16495a42e78543e7